### ISSUE TITLE
Misleading package name

### ISSUE THREAD

**Issue by ankon** [awspilot/cli-lambda-deploy#3]
The name `aws-lambda` in [package.json](../tree/master/package.json) seems to be a rather unfortunate name:

* There's https://www.npmjs.com/package/@types/aws-lambda which exists since a long time, and contains completely unrelated content.
* The name `aws-lambda` doesn't immediately link in my head to `awspilot/cli-lambda-deploy`, and that name describes way better what the package actually contains: A CLI tool for deploying (AWS) lambda functions

Could you please consider changing the `name` entry in package.json?

**Comment by adrianpraja** [comment]
Hi Andreas,


**Npm registry data is immutable, meaning once published, a package cannot change.**

This github repository contains a package  [aws-lambda](https://www.npmjs.com/package/aws-lambda) which was published to the npm registry more than 6 years ago.

At some point I've submited a ticket to npm registry and ask them to remove the aws-lambda package,
not knowing that it actually has a lot of installs ( which btw. I have no idea where they come from, thought they were fake )

Npm replied saying that installs are genuine and they would not take down `aws-lambda` package.

**Comment by ankon** [comment]
It's difficult to understand the history of this github repository -- the first commit seems to be 7f499b0, which was last year. But, indeed there are versions marked as deprecated in npmjs which I missed. I went to the sources of the contents deployed as v0.0.1 in npmjs of the aws-lambda package, and they seem to be coming from the repository https://github.com/awspilot/aws-lambda, which started out as a fork(?) of https://github.com/motdotla/node-lambda and is now deprecated. So I guess awspilot/cli-lambda-deploy at one point was a fork/copy/... of this.

Anyways, indeed this then would indicate that you do have the package name `aws-lambda` already for the longer time, and it is actually the `@types/aws-lambda` package that is doing something slightly off (their first version was 2016-08-11. 

For anyone finding this issue: The reason why I'm looking into this is that TypeScript code I have uses this import:
`import { Handler } from 'aws-lambda'`
The dependencies in the package.json file point to `@types/aws-lambda`, and there is no dependency on the `aws-lambda` package declared.

**Comment by adrianpraja** [comment]
Indeed `aws-lambda` was initially a fork and later published from a new repository as it was no longer based on the initial fork.

You are actually looking for `@types/aws-lambda` which is a different package


I belive your code 
```
import { Handler } from 'aws-lambda'
```

should actually be
```
import { Handler } from '@types/aws-lambda'
```

**Comment by SachinShekhar** [comment]
@ankon You can tweak the module resolution behaviour using `tsconfig.json` if you've problem with that.

@adrianpraja `import { Handler } from '@types/aws-lambda'` isn't standard way. Won't work with standard configuration.

**Comment by adrianpraja** [comment]
SachinShekhar , my mistake, I didnt even check the `@types/aws-lambda` for the correct use.
I just assumed @ankon got the wrong package name in his import due to similar names.

**Comment by ankon** [comment]
Guys, thanks -- but I do know how to import packages in TypeScript. :)

My problem here is not _my_ problem per se, my problem is that the naming convention of the @types/ package is broken, and that that is misleading for anyone depending on these packages. I guess for that case a reasonable way forward could be to mention it in READMEs, for example.

But let's continue this in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/50151, which is about the package with the broken naming, going by the age of the packages involved. :)

**Comment by timothymathison** [comment]
I gather that this package does not meet NPM's [unpublish requirements](https://docs.npmjs.com/policies/unpublish).

Might I suggest [deprecating](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions) it though and adding a clarifying message to reduce confusion? Most likely a lot of the downloads of the package are the result of confusion between this and the `@types/aws-lambda` package.

**Comment by florianakos** [comment]
This seems to cause issues for us now when we use NX that tries to automatically resolve dependencies and put it to the packages.json "dependencies" for a package it's generating to be published to NPM.

As a result of NX seeing `import { Handler } from 'aws-lambda'` in code, it adds `aws-lambda@latest` to the package.json which is very annoying and has to be somehow fixed. Would have been nice if this problem didn't even exist.

**Comment by vanhanenjjv** [comment]
Just removed this package from a project I work on. The `aws-lambda` package should be deprecated with a message to alert potential misinstalls.

**Comment by ankon** [comment]
Small update for anyone finding this and searching for an appropriate approach: Use `import *type* { AwsLambdaTypeYouNeed } from "aws-lambda"`

... and the check dependencies to only include @types/aws-lambda.
