### ISSUE TITLE
Confusing npm package name - aws-lambda

### ISSUE THREAD

**Issue by PeterAronZentai** [awspilot/cli-lambda-deploy#5]
This tools is published  on npmjs as `aws-lambda` - which in its naming collides with `@types/aws-lambda` from AWS, while in the meantime is a match with the package repo name whitch is `cli-lambda-deploy`. 

Considering that this tool is indeed a cli deploy tool - and it hs nothing to do with lambda development - you might wanna consider renaming your package on npmjs?

Also, is this project dead? No updates for over a year now. If so, you might as well mention this in your README.md?

**Comment by PeterAronZentai** [comment]
just seeing this has been raised already and apparently there is no solution.

**Comment by adrianpraja** [comment]
npm packages are immutable, thus can not be renamed or removed, only thing npm registry can to is to transger the ownership to NPM and they will have it delisted from search, funny thing I have no idea why it has so many installs

**Comment by timothymathison** [comment]
> just seeing this has been raised already and apparently there is no solution.

See #3
